#pragma once

// From glfw3.h
#define SOREN_MOUSE_BUTTON_1         0
#define SOREN_MOUSE_BUTTON_2         1
#define SOREN_MOUSE_BUTTON_3         2
#define SOREN_MOUSE_BUTTON_4         3
#define SOREN_MOUSE_BUTTON_5         4
#define SOREN_MOUSE_BUTTON_6         5
#define SOREN_MOUSE_BUTTON_7         6
#define SOREN_MOUSE_BUTTON_8         7
#define SOREN_MOUSE_BUTTON_LAST      SOREN_MOUSE_BUTTON_8
#define SOREN_MOUSE_BUTTON_LEFT      SOREN_MOUSE_BUTTON_1
#define SOREN_MOUSE_BUTTON_RIGHT     SOREN_MOUSE_BUTTON_2
#define SOREN_MOUSE_BUTTON_MIDDLE    SOREN_MOUSE_BUTTON_3